-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('Battle_pb')


local BATTLEINFO = protobuf.Descriptor();
local BATTLEINFO_BATTLEID_FIELD = protobuf.FieldDescriptor();

BATTLEINFO_BATTLEID_FIELD.name = "battleId"
BATTLEINFO_BATTLEID_FIELD.full_name = ".deepdf.BattleInfo.battleId"
BATTLEINFO_BATTLEID_FIELD.number = 1
BATTLEINFO_BATTLEID_FIELD.index = 0
BATTLEINFO_BATTLEID_FIELD.label = 1
BATTLEINFO_BATTLEID_FIELD.has_default_value = false
BATTLEINFO_BATTLEID_FIELD.default_value = 0
BATTLEINFO_BATTLEID_FIELD.type = 13
BATTLEINFO_BATTLEID_FIELD.cpp_type = 3

BATTLEINFO.name = "BattleInfo"
BATTLEINFO.full_name = ".deepdf.BattleInfo"
BATTLEINFO.nested_types = {}
BATTLEINFO.enum_types = {}
BATTLEINFO.fields = {BATTLEINFO_BATTLEID_FIELD}
BATTLEINFO.is_extendable = false
BATTLEINFO.extensions = {}

BattleInfo = protobuf.Message(BATTLEINFO)

