-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('Login_pb')


local ACCOUNTINFO = protobuf.Descriptor();
local ACCOUNTINFO_NAME_FIELD = protobuf.FieldDescriptor();
local ACCOUNTINFO_PASSWD_FIELD = protobuf.FieldDescriptor();
local ACCOUNTINFO_ID_FIELD = protobuf.FieldDescriptor();
local LOGINRES = protobuf.Descriptor();
local LOGINRES_RESULT_FIELD = protobuf.FieldDescriptor();
local LOGINRES_PORT_FIELD = protobuf.FieldDescriptor();
local LOGINRES_HOST_FIELD = protobuf.FieldDescriptor();
local LOGINRES_ID_FIELD = protobuf.FieldDescriptor();

ACCOUNTINFO_NAME_FIELD.name = "name"
ACCOUNTINFO_NAME_FIELD.full_name = ".deepdf.AccountInfo.name"
ACCOUNTINFO_NAME_FIELD.number = 1
ACCOUNTINFO_NAME_FIELD.index = 0
ACCOUNTINFO_NAME_FIELD.label = 1
ACCOUNTINFO_NAME_FIELD.has_default_value = false
ACCOUNTINFO_NAME_FIELD.default_value = ""
ACCOUNTINFO_NAME_FIELD.type = 9
ACCOUNTINFO_NAME_FIELD.cpp_type = 9

ACCOUNTINFO_PASSWD_FIELD.name = "passwd"
ACCOUNTINFO_PASSWD_FIELD.full_name = ".deepdf.AccountInfo.passwd"
ACCOUNTINFO_PASSWD_FIELD.number = 2
ACCOUNTINFO_PASSWD_FIELD.index = 1
ACCOUNTINFO_PASSWD_FIELD.label = 1
ACCOUNTINFO_PASSWD_FIELD.has_default_value = false
ACCOUNTINFO_PASSWD_FIELD.default_value = ""
ACCOUNTINFO_PASSWD_FIELD.type = 9
ACCOUNTINFO_PASSWD_FIELD.cpp_type = 9

ACCOUNTINFO_ID_FIELD.name = "id"
ACCOUNTINFO_ID_FIELD.full_name = ".deepdf.AccountInfo.id"
ACCOUNTINFO_ID_FIELD.number = 3
ACCOUNTINFO_ID_FIELD.index = 2
ACCOUNTINFO_ID_FIELD.label = 1
ACCOUNTINFO_ID_FIELD.has_default_value = false
ACCOUNTINFO_ID_FIELD.default_value = 0
ACCOUNTINFO_ID_FIELD.type = 13
ACCOUNTINFO_ID_FIELD.cpp_type = 3

ACCOUNTINFO.name = "AccountInfo"
ACCOUNTINFO.full_name = ".deepdf.AccountInfo"
ACCOUNTINFO.nested_types = {}
ACCOUNTINFO.enum_types = {}
ACCOUNTINFO.fields = {ACCOUNTINFO_NAME_FIELD, ACCOUNTINFO_PASSWD_FIELD, ACCOUNTINFO_ID_FIELD}
ACCOUNTINFO.is_extendable = false
ACCOUNTINFO.extensions = {}
LOGINRES_RESULT_FIELD.name = "result"
LOGINRES_RESULT_FIELD.full_name = ".deepdf.LoginRes.result"
LOGINRES_RESULT_FIELD.number = 1
LOGINRES_RESULT_FIELD.index = 0
LOGINRES_RESULT_FIELD.label = 1
LOGINRES_RESULT_FIELD.has_default_value = false
LOGINRES_RESULT_FIELD.default_value = false
LOGINRES_RESULT_FIELD.type = 8
LOGINRES_RESULT_FIELD.cpp_type = 7

LOGINRES_PORT_FIELD.name = "port"
LOGINRES_PORT_FIELD.full_name = ".deepdf.LoginRes.port"
LOGINRES_PORT_FIELD.number = 2
LOGINRES_PORT_FIELD.index = 1
LOGINRES_PORT_FIELD.label = 1
LOGINRES_PORT_FIELD.has_default_value = false
LOGINRES_PORT_FIELD.default_value = 0
LOGINRES_PORT_FIELD.type = 13
LOGINRES_PORT_FIELD.cpp_type = 3

LOGINRES_HOST_FIELD.name = "host"
LOGINRES_HOST_FIELD.full_name = ".deepdf.LoginRes.host"
LOGINRES_HOST_FIELD.number = 3
LOGINRES_HOST_FIELD.index = 2
LOGINRES_HOST_FIELD.label = 1
LOGINRES_HOST_FIELD.has_default_value = false
LOGINRES_HOST_FIELD.default_value = ""
LOGINRES_HOST_FIELD.type = 9
LOGINRES_HOST_FIELD.cpp_type = 9

LOGINRES_ID_FIELD.name = "id"
LOGINRES_ID_FIELD.full_name = ".deepdf.LoginRes.id"
LOGINRES_ID_FIELD.number = 4
LOGINRES_ID_FIELD.index = 3
LOGINRES_ID_FIELD.label = 1
LOGINRES_ID_FIELD.has_default_value = false
LOGINRES_ID_FIELD.default_value = 0
LOGINRES_ID_FIELD.type = 13
LOGINRES_ID_FIELD.cpp_type = 3

LOGINRES.name = "LoginRes"
LOGINRES.full_name = ".deepdf.LoginRes"
LOGINRES.nested_types = {}
LOGINRES.enum_types = {}
LOGINRES.fields = {LOGINRES_RESULT_FIELD, LOGINRES_PORT_FIELD, LOGINRES_HOST_FIELD, LOGINRES_ID_FIELD}
LOGINRES.is_extendable = false
LOGINRES.extensions = {}

AccountInfo = protobuf.Message(ACCOUNTINFO)
LoginRes = protobuf.Message(LOGINRES)

